language: php
php:      [ "5.4" ]
script:   "./reset.sh; ./bin/service & phpunit -c app/; bin/behat --stop-on-failure"

before_script:
    - sudo apt-get update -qq
    - sudo apt-get install apache2 libapache2-mod-fastcgi

    # Mailcatcher server
    - gem install mailcatcher
    - mailcatcher

     # PHP-FPM
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
    - sudo a2enmod rewrite actions fastcgi alias
    - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

    # configure apache virtual hosts
    - sudo cp -f .travis.vhost.conf /etc/apache2/sites-available/default
    - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)/web?g" --in-place /etc/apache2/sites-available/default
    - sudo service apache2 restart

    # XVFB
    - "export DISPLAY=:99.0"
    - "Xvfb :99.0 -extension RANDR > /dev/null &"

    # Window manager
    - "sudo apt-get install fluxbox -y --force-yes"
    - "fluxbox &"

    # Selenium server
    - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.39.0.jar"
    - "java -jar selenium-server-standalone-2.39.0.jar > /dev/null 2>/dev/null &"

    # Firefox
    - sudo apt-get install -y --force-yes firefox
