language: php
php:      [ "5.4" ]
script:   "./test.sh"

# Inspired from http://knpuniversity.com/screencast/question-answer-day/travis-ci
before_script:
    - sudo apt-get update -qq

    # Compass
    - gem install compass

    # Mailcatcher server
    - gem install mailcatcher
    - mailcatcher

    # Apache
    - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl php5-sqlite sqlite3
    - sudo sed -i -e "s,/var/www,$(pwd)/web,g" /etc/apache2/sites-available/default
    - sudo sed -i -e "s,AllowOverride None,AllowOverride All,g" /etc/apache2/sites-available/default
    - cat /etc/apache2/envvars
    - sudo sed -i -e "s,www-data,$(whoami),g" /etc/apache2/envvars
    - sudo sed -i -e "/DocumentRoot/i\ServerName gitonomy.dev" /etc/apache2/sites-available/default
    - echo "127.0.0.1 gitonomy.dev" | sudo tee -a /etc/hosts
    - sudo a2enmod rewrite
    - sudo a2enmod php5
    - sudo /etc/init.d/apache2 stop
    - sudo rm -rf /var/lock/apache2
    - sudo /etc/init.d/apache2 start

    # XVFB
    - "export DISPLAY=:99.0"
    - sh -e /etc/init.d/xvfb start

    # Selenium server
    - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.39.0.jar"
    - "java -jar selenium-server-standalone-2.39.0.jar > /dev/null &"
    - "wget http://chromedriver.googlecode.com/files/chromedriver_linux32_23.0.1240.0.zip && unzip chromedriver_linux32_23.0.1240.0.zip && sudo mv chromedriver /usr/bin"
