imports:
    - { resource: parameters_dist.yml }
    - { resource: parameters.yml, ignore_errors: true }
    - { resource: security.yml }

parameters:
    assetic.filter.compass.images_dir: %kernel.root_dir%/../web/images
    assetic.filter.compass.http_path:  /images

framework:
    #esi:             ~
    translator:      { fallback: en_US }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      ~
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  en_US
    session:         ~

# Gitonomy core
gitonomy_core:
    repository_path:   %repository_path%
    config_defaults:
        name:              Gitonomy
        baseline:          git repositories inside your infrastructure
        ssh_access:        john@nowhere
        locale:            en_US
        open_registration: true
        mailer_transport:  smtp
        mailer_port:       1025
        mailer_host:       localhost
        mailer_user:       username
        mailer_password:   password
        mailer_auth_mode:  basic
        mailer_encryption: ssl
        mailer_from_name:  Gitonomy
        mailer_from_email: gitonomy@nowhere

# Gitonomy Git
gitonomy_git:
    twig_extension:
        enabled: true
        routes_names:
            commit:               project_commit
            branch:               project_history
            tag:                  project_history
            tree:                 project_tree
        routes_args:
            commit_repository:    slug
            commit_hash:          hash
            branch_repository:    slug
            branch_name:          branch
            tag_repository:       slug
            tag_name:             branch
            tree_repository:      slug
            tree_revision:        revision
            tree_path:            path

# Gitonomy jobs
gitonomy_job:
    job_classes:
        delete_reference: Gitonomy\Bundle\CoreBundle\Job\DeleteReferenceJob
        update_ssh_keys:  Gitonomy\Bundle\CoreBundle\Job\UpdateSshKeysJob

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources: [ "GitonomyWebsiteBundle::form.html.twig" ]


# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar
        lessphp:
            apply_to: "\.less$"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Buzz Configuration
buzz:
    browsers:
        gitonomy:
            client:
                name: curl
                timeout: 5
            host: http://gitonomy.com
            message_factory: Gitonomy\Component\Buzz\Message\Factory\JsonMessageFactory
