imports:
    - { resource: config_dev.yml }

gitonomy_core:
    async_storage: direct

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

twig:
    exception_controller:     Gitonomy\Bundle\WebsiteBundle\Controller\ErrorController::showAction

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        dbname:   %database_name%_test
