parameters:
  # Database
  database_driver:   pdo_mysql
  database_host:     localhost
  database_port:     ~
  database_name:     gitonomy
  database_user:     root
  database_password: ~

  # Mailer
  mailer_transport:  smtp
  mailer_encryption: ssl
  mailer_auth_mode:  login
  mailer_host:       localhost
  mailer_user:       ~
  mailer_password:   ~

  # Security
  secret:            ThisTokenIsNotSoSecretChangeIt

  # Localisation
  locale:            en_US

  # System
  repository_path:   %kernel.root_dir%/cache/repositories
  ssh_access:        alex@localhost

  # Your project
  project_name:      gitonomy.sample
  project_baseline:  Git repositories inside your infrastructure
  open_registration: true
  mailer_from_name:  gitonomy.sample
  mailer_from_email: noreply@example.org
